var celebrityList = {
  "Brad Pitt": "https://commons.wikimedia.org/wiki/File:Brad_Pitt_2012.jpg",
  "Jennifer Aniston": "https://commons.wikimedia.org/wiki/File:JenniferAnistonHWoFFeb2012.jpg",
  "Leonardo DiCaprio": "https://commons.wikimedia.org/wiki/File:Leonardo_DiCaprio_October_2016.jpg",
  "Angelina Jolie": "https://commons.wikimedia.org/wiki/File:Angelina_Jolie_2_June_2014_(cropped).jpg",
  "Tom Hanks": "https://commons.wikimedia.org/wiki/File:Tom_Hanks_at_the_Elvis_Premiere_2022.jpg",
  "Scarlett Johansson": "https://commons.wikimedia.org/wiki/File:Scarlett_Johansson_in_Kuwait_02_(square).jpg",
  "Will Smith": "https://commons.wikimedia.org/wiki/File:TechCrunch_Disrupt_2019_(48834434641)_(cropped).jpg",
  "Julia Roberts": "https://commons.wikimedia.org/wiki/File:Julia_Roberts_2011_Shankbone_3.JPG",
  "Dwayne Johnson": "https://commons.wikimedia.org/wiki/File:Dwayne_Johnson_2,_2013.jpg",
  "Charlize Theron": "https://commons.wikimedia.org/wiki/File:Charlize_Theron_Cannes_2015_6.jpg",
  "George Clooney": "https://commons.wikimedia.org/wiki/File:George_Clooney_2016.jpg",
  "Meryl Streep": "https://commons.wikimedia.org/wiki/File:Meryl_Streep_December_2018.jpg",
  "Ryan Reynolds": "https://commons.wikimedia.org/wiki/File:Deadpool_2_Japan_Premiere_Red_Carpet_Ryan_Reynolds_(cropped).jpg",
  "Sandra Bullock": "https://commons.wikimedia.org/wiki/File:Sandra_Bullock_2018_(cropped).jpg",
  "Chris Hemsworth": "https://commons.wikimedia.org/wiki/File:Chris_Hemsworth_by_Gage_Skidmore_2_(cropped).jpg",
  "Emma Stone": "https://commons.wikimedia.org/wiki/File:Emma_Stone_at_Maniac_UK_premiere_(cropped).jpg",
  "Robert Downey Jr.": "https://commons.wikimedia.org/wiki/File:Robert_Downey_Jr_2014_Comic_Con_(cropped).jpg",
  "Nicole Kidman": "https://commons.wikimedia.org/wiki/File:Nicole_Kidman_Cannes_2017_2.jpg",
  "Johnny Depp": "https://commons.wikimedia.org/wiki/File:Johnny_Depp_2020.jpg",
  "Jennifer Lawrence": "https://commons.wikimedia.org/wiki/File:Jennifer_Lawrence_SDCC_2015_X-Men.jpg",
  "Bradley Cooper": "https://commons.wikimedia.org/wiki/File:Bradley_Cooper_(11242795155)_(cropped).jpg",
  "Gal Gadot": "https://commons.wikimedia.org/wiki/File:Gal_Gadot_cropped_lighting_corrected.jpg",
  "Chris Evans": "https://commons.wikimedia.org/wiki/File:Mark_Kassen,_Tony_C%C3%A1rdenas_and_Chris_Evans_(cropped).jpg",
  "Margot Robbie": "https://commons.wikimedia.org/wiki/File:Margot_Robbie_2018_(cropped).png",
  "Matt Damon": "https://commons.wikimedia.org/wiki/File:Matt_Damon,_Berlinale_2023_(cropped).jpg",
  "Natalie Portman": "https://commons.wikimedia.org/wiki/File:Natalie_Portman_in_2005_(cropped).jpg",
  "Hugh Jackman": "https://commons.wikimedia.org/wiki/File:Logan_Japan_Premiere_Red_Carpet-_Hugh_Jackman_(38445328406)_(rotated).jpg",
  "Anne Hathaway": "https://commons.wikimedia.org/wiki/File:Anne_Hathaway_at_MIFF_(cropped).jpg",
  "Michael B Jordan": "https://commons.wikimedia.org/wiki/File:2018-05-12-_Cannes-L%27acteur_Michael_B._Jordan-2721_(42075892224).jpg",
  "Cate Blanchett": "https://commons.wikimedia.org/wiki/File:Cate_Blanchett_Berlinale_2023_(cropped).jpg",
  "Idris Elba": "https://commons.wikimedia.org/wiki/File:Idris_Elba-4580_(cropped).jpg",
  "Jennifer Lopez": "https://commons.wikimedia.org/wiki/File:Jennifer_Lopez_at_GLAAD_Media_Awards_(cropped).jpg",
  "Mark Wahlberg": "https://commons.wikimedia.org/wiki/File:Mark_Wahlberg_2017.jpg",
  "Adele": "https://commons.wikimedia.org/wiki/File:Adele_for_Vogue_in_2021.png",
  "Ryan Gosling": "https://commons.wikimedia.org/wiki/File:Ryan_Gosling_by_Gage_Skidmore.jpg",
  "Halle Berry": "https://commons.wikimedia.org/wiki/File:Halle_Berry_by_Gage_Skidmore.jpg",
  "Emma Watson": "https://commons.wikimedia.org/wiki/File:Emma_Watson_2013.jpg",
  "Tom Cruise": "https://commons.wikimedia.org/wiki/File:Tom_Cruise_by_Gage_Skidmore_2.jpg",
  "Amy Adams": "https://commons.wikimedia.org/wiki/File:Amy_Adams_UK_Nocturnal_Animals_Premiere_(cropped).jpg",
  "Samuel L Jackson": "https://commons.wikimedia.org/wiki/File:SamuelLJackson.jpg",
  "Gwyneth Paltrow": "https://commons.wikimedia.org/wiki/File:Gwyneth_Paltrow_face.jpg"
};