var famousScientists = {
  "Albert Einstein": "https://commons.wikimedia.org/wiki/File:Albert_Einstein_Head.jpg",
  "Marie Curie": "https://commons.wikimedia.org/wiki/File:Mariecurie.jpg",
  "Isaac Newton": "https://commons.wikimedia.org/wiki/File:GodfreyKneller-IsaacNewton-1689.jpg",
  "Charles Darwin": "https://commons.wikimedia.org/wiki/File:Charles_Darwin_01.jpg",
  "Nikola Tesla": "https://commons.wikimedia.org/wiki/File:Tesla_circa_1890.jpeg",
  "Galileo Galilei": "https://commons.wikimedia.org/wiki/File:Justus_Sustermans_-_Portrait_of_Galileo_Galilei,_1636.jpg",
  "Stephen Hawking": "https://commons.wikimedia.org/wiki/File:Stephen_Hawking.StarChild.jpg",
  "Leonardo da Vinci": "https://commons.wikimedia.org/wiki/File:Portrait_of_Leonardo_da_Vinci_(from_Characaturas_by_Leonardo_da_Vinci,_from_Drawings_by_Wincelslaus_Hollar,_out_of_the_Portland_Museum)_MET_DP824104.jpg",
  "Jane Goodall": "https://commons.wikimedia.org/wiki/File:Jane-goodall.jpg",
  "Alexander Fleming": "https://commons.wikimedia.org/wiki/File:Alexander_Fleming_1945.jpg",
  "Carl Sagan": "https://commons.wikimedia.org/wiki/File:Carl_Sagan_Planetary_Society.JPG",
  "Rosalind Franklin": "https://commons.wikimedia.org/wiki/File:Rosalind-franklin-in-paris_crop.jpg",
  "Neil deGrasse Tyson": "https://commons.wikimedia.org/wiki/File:Neil_deGrasse_Tyson_at_Howard_University_September_28,_2010_(cropped_to_shoulders).jpg",
  "Louis Pasteur": "https://commons.wikimedia.org/wiki/File:Louis_Pasteur,_foto_av_Paul_Nadar,_Crisco_edit.jpg",
  "Alan Turing": "https://commons.wikimedia.org/wiki/File:Alan_Turing_portr%C3%A9.jpg",
  "Max Planck": "https://commons.wikimedia.org/wiki/File:Max_Planck_(1858-1947).jpg",
  "Edwin Hubble": "https://commons.wikimedia.org/wiki/File:Studio_portrait_photograph_of_Edwin_Powell_Hubble_(cropped).JPG",
  "Nikolaus Copernicus": "https://commons.wikimedia.org/wiki/File:Nikolaus_Kopernikus.jpg",
  "Richard Feynman": "https://commons.wikimedia.org/wiki/File:Richard_Feynman_1959.png",
  "Francis Crick": "https://commons.wikimedia.org/wiki/File:Francis_Crick_1995.jpg",
  "Niels Bohr": "https://commons.wikimedia.org/wiki/File:Niels_Bohr_-_LOC_-_ggbain_-_35303.png",
  "Erwin Schrödinger": "https://commons.wikimedia.org/wiki/File:Erwin_Schr%C3%B6dinger_-_Narodowe_Archiwum_Cyfrowe_(1-E-939).jpg",
  "Paul Dirac": "https://commons.wikimedia.org/wiki/File:Paul_Dirac,_1933.jpg",
  "Edward Witten": "https://commons.wikimedia.org/wiki/File:Edward_Witten.jpg",
  "John Wheeler": "https://commons.wikimedia.org/wiki/File:John_Archibald_Wheeler_1985.jpg",
  "Steven Weinberg": "https://commons.wikimedia.org/wiki/File:Steven_weinberg_2010.jpg",
  "Brian Greene": "https://commons.wikimedia.org/wiki/File:Brian_Greene,_February_28,_2014_(cropped).jpg",
  "Michio Kaku": "https://commons.wikimedia.org/wiki/File:Michio_Kaku_Presentation-cropped.jpg"
};