var famousMusicians = {
  "Michael Jackson": "https://commons.wikimedia.org/wiki/File:Michael_Jackson_Dangerous_World_Tour_1993.jpg",
  "The Beatles": "https://commons.wikimedia.org/wiki/File:Beatles_ad_1965_just_the_beatles_crop.jpg",
  "Madonna": "https://commons.wikimedia.org/wiki/File:Madonna_at_the_premiere_of_I_Am_Because_We_Are.jpg",
  "Elvis Presley": "https://commons.wikimedia.org/wiki/File:Elvis_Presley_1970.jpg",
  "Beyoncé": "https://commons.wikimedia.org/wiki/File:Beyonc%C3%A9_-_Tottenham_Hotspur_Stadium_-_1st_June_2023_(13_of_118)_(52945303842)_(face_cropped).jpg",
  "Freddie Mercury": "https://commons.wikimedia.org/wiki/File:Freddie_Mercury_performing_in_New_Haven,_CT,_November_1977.jpg",
  "Bob Dylan": "https://commons.wikimedia.org/wiki/File:Bob_Dylan_-_Azkena_Rock_Festival_2010_2.jpg",
  "David Bowie": "https://commons.wikimedia.org/wiki/File:David_Bowie_-_1983_Let%27s_Dance_Promo_004.jpg",
  "Aretha Franklin": "https://commons.wikimedia.org/wiki/File:Aretha_Franklin_1968.jpg",
  "Prince": "https://commons.wikimedia.org/wiki/File:Prince_at_Coachella_(cropped).jpg",
  "Johnny Cash": "https://commons.wikimedia.org/wiki/File:Johnny_Cash_Promotional_Photo.jpg",
  "Jimi Hendrix": "https://commons.wikimedia.org/wiki/File:Jimi_Hendrix_(1967).jpg",
  "Frank Sinatra": "https://commons.wikimedia.org/wiki/File:Frank_Sinatra_(1942_photo_portrait).jpg",
  "Whitney Houston": "https://commons.wikimedia.org/wiki/File:Whitney_Houston_Welcome_Home_Heroes_1_cropped.jpg",
  "Stevie Wonder": "https://commons.wikimedia.org/wiki/File:Stevie_Wonder_June_30,_Montreal.jpg",
  "Janis Joplin": "https://commons.wikimedia.org/wiki/File:Janis_Joplin_seated_1970.JPG",
  "Nina Simone": "https://commons.wikimedia.org/wiki/File:Nina_Simone_1965_-_restoration1.jpg",
  "Bruce Springsteen": "https://commons.wikimedia.org/wiki/File:Bruce_Springsteen_1988.jpg",
  "Queen": "https://commons.wikimedia.org/wiki/File:Queen_sheratonhotel_bsas.jpg",
  "Taylor Swift": "https://commons.wikimedia.org/wiki/File:Taylor_Swift_2009.jpg",
  "Drake": "https://commons.wikimedia.org/wiki/File:Drake_July_2016.jpg",
  "Miles Davis": "https://commons.wikimedia.org/wiki/File:Miles_Davis_by_Palumbo.jpg",
  "Amy Winehouse": "https://commons.wikimedia.org/wiki/File:Amy_Winehouse_in_2008.jpg",
  "Ludwig van Beethoven": "https://commons.wikimedia.org/wiki/File:Beethoven.jpg",
  "Johnny Marr": "https://commons.wikimedia.org/wiki/File:Johnny_Marr_University_of_Salford_2012_crop.jpg",
  "Ella Fitzgerald": "https://commons.wikimedia.org/wiki/File:Ella_Fitzgerald_1962.JPG",
  "Eric Clapton": "https://commons.wikimedia.org/wiki/File:Eric_Clapton_1978.jpg",
  "Billie Holiday": "https://commons.wikimedia.org/wiki/File:(Portrait_of_Billie_Holiday_and_Mister,_Downbeat,_New_York,_N.Y.,_ca._Feb._1947)_(LOC)_(5020400274)_(cropped).jpg",
  "Louis Armstrong": "https://commons.wikimedia.org/wiki/File:Louis_Armstrong_restored.jpg",
  "Carlos Santana": "https://commons.wikimedia.org/wiki/File:Carlos_Santana_2.jpg"
};