var fastFoodItems = {
  "Cheeseburger": "https://commons.wikimedia.org/wiki/File:Cheeseburger.jpg",
  "French fries": "https://commons.wikimedia.org/wiki/File:BK-French-Fries.jpg",
  "Chicken nuggets": "https://commons.wikimedia.org/wiki/File:Chicken_Nuggets.jpg",
  "Hot dog": "https://commons.wikimedia.org/wiki/File:Hot_dog_with_mustard.png",
  "Onion rings": "https://commons.wikimedia.org/wiki/File:Burger_King_Onion_Rings_in_Bag_(19043880786).jpg",
  "Milkshake": "https://commons.wikimedia.org/wiki/File:Strawberry_milk_shake_(cropped).jpg",
  "Taco": "https://commons.wikimedia.org/wiki/File:Best_tacos_in_NE_Louisiana.jpg",
  "Fried chicken": "https://commons.wikimedia.org/wiki/File:Fried-Chicken-Set.jpg",
  "Burrito": "https://commons.wikimedia.org/wiki/File:Burrito.JPG",
  "Ice cream cone": "https://commons.wikimedia.org/wiki/File:Dickey%27s_BBQ_Pit_Soft_Serve_Ice_Cream_Cone_(20070080633).jpg",
  "Nachos": "https://commons.wikimedia.org/wiki/File:Nachos-cheese.jpg",
  "Chicken salad sandwich": "https://commons.wikimedia.org/wiki/File:Chicken_salad_sandwich_01.jpg",
  "Mozzarella sticks": "https://commons.wikimedia.org/wiki/File:2023-04-10_17_23_29_Mozzarella_sticks_from_Wawa_in_Westampton_Township,_Burlington_County,_New_Jersey.jpg",
  "Sushi roll": "https://commons.wikimedia.org/wiki/File:California_Sushi_(26571101885).jpg",
  "Donut": "https://commons.wikimedia.org/wiki/File:Glazed-Donut.jpg",
  "Popcorn chicken": "https://commons.wikimedia.org/wiki/File:Popcorn_Chicken_(Fresno_CA)_KFC.jpg",
  "Pretzel": "https://commons.wikimedia.org/wiki/File:Crunchy_Pretzel_(33448762094).jpg",
  "Fish and chips": "https://commons.wikimedia.org/wiki/File:Modern_fish_and_chips_(8368723726).jpg",
  "Chicken wings": "https://commons.wikimedia.org/wiki/File:16-03-17-Chicken-Wings-Burger-King-RalfR-WP_20160317_001.jpg",
  "BBQ ribs": "https://commons.wikimedia.org/wiki/File:BBQ_RIBS_pork_side_ribs.jpg",
  "Corn dog": "https://commons.wikimedia.org/wiki/File:Corn_dog_001.jpg",
  "Chili cheese fries": "https://commons.wikimedia.org/wiki/File:Chili_cheese_fries_mexico.jpg",
  "Cinnamon roll": "https://commons.wikimedia.org/wiki/File:Cinnamon_roll_and_fork,_2009-11-01.jpg"
};
