var fastFoodRestaurants = {
  "McDonald's": "https://commons.wikimedia.org/wiki/File:Flag_of_the_McDonald%27s_Corporation.svg",
  "Burger King": "",
  "Wendy's": "",
  "KFC": "",
  "Subway": "",
  "Taco Bell": "",
  "Pizza Hut": "",
  "Domino's Pizza": "",
  "Starbucks": "",
  "Chick-fil-A": "",
  "Dunkin'": "",
  "Popeyes": "",
  "Arby's": "",
  "Jack in the Box": "",
  "In-N-Out Burger": "",
  "Sonic Drive-In": "",
  "Carl's Jr.": "",
  "Five Guys": "",
  "Panera Bread": "",
  "Jimmy John's": "",
  "Dairy Queen": "",
  "Panda Express": "",
  "Little Caesars": "",
  "Krispy Kreme": "",
  "Whataburger": "",
  "Hardee's": "",
  "White Castle": "",
  "Culver's": "",
  "Checkers": "",
  "Zaxby's": "",
  "A&W Restaurants": "",
  "Long John Silver's": "",
  "Firehouse Subs": "",
  "Jersey Mike's Subs": "",
  "Tim Hortons": "",
  "Qdoba Mexican Eats": "",
  "Raising Cane's": "",
  "El Pollo Loco": "",
  "Cinnabon": "",
  "Jollibee": "",
  "Sbarro": ""
};