var retroGamingItems = {
  "Super Mario Bros.": "https://commons.wikimedia.org/wiki/File:Super_Mario_Bros._coin_edited.svg",
  "Pac-Man": "https://commons.wikimedia.org/wiki/File:Pac-Man_Cutscene.svg",
  "Donkey Kong": "",
  "The Legend of Zelda": "",
  "Sonic the Hedgehog": "",
  "Space Invaders": "",
  "Tetris": "",
  "Pong": "",
  "Mega Man": "",
  "Street Fighter II": "",
  "Super Metroid": "",
  "Castlevania": "",
  "Final Fantasy VII": "",
  "Pokémon Red/Blue": "",
  "Duck Hunt": "",
  "Mortal Kombat": "",
  "Galaga": "",
  "Contra": "",
  "Metal Gear Solid": "",
  "Double Dragon": "",
  "Pitfall!": "",
  "Super Mario Kart": "",
  "GoldenEye 007": "",
  "Super Smash Bros.": "",
  "Doom": "",
  "Ghosts 'n Goblins": "",
  "Earthbound": "",
  "Resident Evil": "",
  "The Secret of Monkey Island": "",
  "Maniac Mansion": "",
  "Bubble Bobble": "",
  "Ninja Gaiden": "",
  "Gradius": "",
  "Mega Man X": "",
  "Chrono Trigger": "",
  "Mortal Kombat II": "",
  "Donkey Kong Country": "",
  "Excitebike": "",
  "The Oregon Trail": ""
};