var speciesList = {
  "African elephant": "https://commons.wikimedia.org/wiki/File:African_Bush_Elephant.jpg",
  "Blue whale": "https://commons.wikimedia.org/wiki/File:Blue-Whale-0009.jpg",
  "Bengal tiger": "https://commons.wikimedia.org/wiki/File:Panthera_tigris_tigris.jpg",
  "Bald eagle": "https://commons.wikimedia.org/wiki/File:Weisskopf_Seeadler_haliaeetus_leucocephalus_8_amk.jpg",
  "Giant panda": "https://commons.wikimedia.org/wiki/File:Grosser_Panda.JPG",
  "Green sea turtle": "https://commons.wikimedia.org/wiki/File:Green_turtle_swimming_over_coral_reefs_in_Kona.jpg",
  "Snow leopard": "https://commons.wikimedia.org/wiki/File:Irbis4.JPG",
  "Red fox": "https://commons.wikimedia.org/wiki/File:R%C3%B8d_r%C3%A6v_(Vulpes_vulpes).jpg",
  "Orca": "https://commons.wikimedia.org/wiki/File:Killerwhales_jumping.jpg",
  "Chimpanzee": "https://commons.wikimedia.org/wiki/File:Pan_troglodytes_(male).jpg",
  "Koala": "https://commons.wikimedia.org/wiki/File:Koala_climbing_tree.jpg",
  "Emperor penguin": "https://commons.wikimedia.org/wiki/File:Aptenodytes_forsteri_-Snow_Hill_Island,_Antarctica_-adults_and_juvenile-8.jpg",
  "Gray wolf": "https://commons.wikimedia.org/wiki/File:Eurasian_wolf_2.jpg",
  "Great white shark": "https://commons.wikimedia.org/wiki/File:Great_white_shark_south_africa.jpg",
  "Red-crowned crane": "https://commons.wikimedia.org/wiki/File:Grus_japonensis_-Marwell_Wildlife,_Hampshire,_England-8a.jpg",
  "Amur leopard": "https://commons.wikimedia.org/wiki/File:Amur_Leopard_Panthera_pardus_orientalis_Facing_Forward_1761px.jpg",
  "Poison dart frog": "https://commons.wikimedia.org/wiki/File:Poison_Dart_Frog_By_Trisha_5.jpg",
  "Komodo dragon": "https://commons.wikimedia.org/wiki/File:Komodo_dragon_(Varanus_komodoensis)_4.jpg",
  "Arctic fox": "https://commons.wikimedia.org/wiki/File:Iceland-1979445_(cropped_3).jpg",
  "Golden eagle": "https://commons.wikimedia.org/wiki/File:%D0%91%D0%B5%D1%80%D0%BA%D1%83%D1%82_(Aquila_chrysaetos).jpg",
  "Giraffe": "https://commons.wikimedia.org/wiki/File:Giraffa_camelopardalis_angolensis.jpg",
  "Kangaroo": "https://commons.wikimedia.org/wiki/File:Kangaroo_Adelaide.jpg",
  "Polar bear": "https://commons.wikimedia.org/wiki/File:Polar_Bear_-_Alaska_(cropped).jpg",
  "Red panda": "https://commons.wikimedia.org/wiki/File:Red_Panda_(24986761703).jpg",
  "Zebra": "https://commons.wikimedia.org/wiki/File:Hungry_zebra.png",
  "Toucan": "https://commons.wikimedia.org/wiki/File:Toucan_Parque-das-Aves.jpg",
  "Cheetah": "Cheetah",
  "Platypus": "https://commons.wikimedia.org/wiki/File:Wild_Platypus_4.jpg",
  "Gorilla": "https://commons.wikimedia.org/wiki/File:Lowland_Gorilla_(8973697544).jpg",
  "Humpback whale": "https://commons.wikimedia.org/wiki/File:Young_Male_Humpback_Whale-Megaptera_novaeangliae_(16819905665).jpg"
};