var sportsList = {
  "Football": "https://commons.wikimedia.org/wiki/File:Virtual_football.jpg",
  "Basketball": "https://commons.wikimedia.org/wiki/File:Carter_vs_Gasol,_Lakers_vs_Magic.jpg",
  "Baseball": "https://commons.wikimedia.org/wiki/File:Douliou_Baseball_012.jpg",
  "Tennis": "https://commons.wikimedia.org/wiki/File:2015_US_Open_Tennis_-_Tournament_-_Richard_Gasquet_(FRA)_(12)_def._Bernard_Tomic_(AUS)_(24)_(21005280588).jpg",
  "Golf": "https://commons.wikimedia.org/wiki/File:Golfer_swing.jpg",
  "Hockey": "https://commons.wikimedia.org/wiki/File:20150207_1850_Ice_Hockey_AUT_SVK_9930.jpg",
  "Cricket": "https://commons.wikimedia.org/wiki/File:Muralitharan_bowling_to_Adam_Gilchrist.jpg",
  "Rugby": "https://commons.wikimedia.org/wiki/File:USO_-_Saracens_-_20151213_-_Maro_Itoje_attacking.jpg",
  "Volleyball": "https://commons.wikimedia.org/wiki/File:Bulgaria-serbia_volley_2012.jpg",
  "Badminton": "https://commons.wikimedia.org/wiki/File:Badminton_Semifinal_Pan_2007.jpg",
  "Table Tennis": "https://commons.wikimedia.org/wiki/File:Ishikawa_and_Fukuhara_at_Table_Tennis_Pro_Tour_Grand_Finals_2011_(2).jpg",
  "Swimming": "https://commons.wikimedia.org/wiki/File:H%C3%A0bit_Saludable.jpg",
  "Boxing": "https://commons.wikimedia.org/wiki/File:JonesvsTrinidad.jpg",
  "Martial Arts": "",
  "Cycling": "https://commons.wikimedia.org/wiki/File:TourDeFrance_2005_07_09.jpg",
  "Wrestling": "https://commons.wikimedia.org/wiki/File:USCGA_Competes_in_2018_NCAA_Division_III_National_Wrestling_Championships_-_Image_7_of_8.jpg",
  "Gymnastics": "https://commons.wikimedia.org/wiki/File:Gym_combination_2.JPG",
  "Formula 1": "https://commons.wikimedia.org/wiki/File:2015_Malaysian_GP_opening_lap.jpg",
  "Motocross": "https://commons.wikimedia.org/wiki/File:Mundial_de_motocross.JPG",
  "Surfing": "https://commons.wikimedia.org/wiki/File:2010_mavericks_competition_edit1.jpg",
  "Skateboarding": "https://commons.wikimedia.org/wiki/File:Stephen_Hill_skateboarding,_Port_Melbourne,_2023.jpg",
  "Snowboarding": "https://commons.wikimedia.org/wiki/File:Ryan_McDonald_2005_Continental_Cup.jpg",
  "Skiing": "https://commons.wikimedia.org/wiki/File:Ski_Famille_-_Family_Ski_Holidays.jpg"
};