var toolsList = {
  "Hammer": "https://commons.wikimedia.org/wiki/File:Claw-hammer.jpg",
  "Screwdriver": "https://commons.wikimedia.org/wiki/File:Big_flat_screwdriver.jpg",
  "Wrench": "https://commons.wikimedia.org/wiki/File:Cl%C3%A9_plate.jpg",
  "Pliers": "https://commons.wikimedia.org/wiki/File:Jewellery_pliers.jpg",
  "Saw": "https://commons.wikimedia.org/wiki/File:Tenon_Saw.jpg",
  "Tape Measure": "https://commons.wikimedia.org/wiki/File:Tape_Measure_25%27_Klein_Tools.jpg",
  "Chisel": "https://commons.wikimedia.org/wiki/File:Chisel_wood_24mm.jpg",
  "Level": "https://commons.wikimedia.org/wiki/File:Tool-level.jpg",
  "Utility Knife": "https://commons.wikimedia.org/wiki/File:Utility_knife.jpg",
  "Clamps": "https://commons.wikimedia.org/wiki/File:Clamps_-_tools.jpg",
  "Sander": "https://commons.wikimedia.org/wiki/File:Sander,_Vlakschuurmachine.jpg",
  "Hacksaw": "https://commons.wikimedia.org/wiki/File:Hacksaw_with_grey_handle.jpg",
  "Caulking Gun": "https://commons.wikimedia.org/wiki/File:Glue_gun_for_cartridge.jpg",
  "Angle Grinder": "https://commons.wikimedia.org/wiki/File:Grinder_diamond_blade.jpg",
  "Paintbrush": "https://commons.wikimedia.org/wiki/File:Paintbrushes.jpg",
  "Staple Gun": "https://commons.wikimedia.org/wiki/File:Staple-gun.jpg",
  "Wire Cutter": "https://commons.wikimedia.org/wiki/File:Wire_cutter_-_Sept._2013.jpg",
  "Mallet": "https://commons.wikimedia.org/wiki/File:Mallet_menuisier.jpg",
  "Adjustable Wrench": "https://commons.wikimedia.org/wiki/File:Adjustable_wrench_-_15_x_2_cm_-_B1.jpg",
  "Soldering Iron": "https://commons.wikimedia.org/wiki/File:Soldering_iron_(UK_Plug).jpg",
  "Pipe Cutter": "https://commons.wikimedia.org/wiki/File:Ratcheting_Plastic_Pipe_Cutters.jpg",
  "Trowel": "https://commons.wikimedia.org/wiki/File:Kielnia_001.JPG",
  "Air Compressor": "https://commons.wikimedia.org/wiki/File:Air_compressor_small_2009.6.15.JPG",
  "Nail Gun": "https://commons.wikimedia.org/wiki/File:Nail_gun_sweden_20030918.jpg",
  "Crowbar": "https://commons.wikimedia.org/wiki/File:Crowbar_without_haft.jpg",
  "File": "https://commons.wikimedia.org/wiki/File:Warding_File.jpg",
  "Sledgehammer": "https://commons.wikimedia.org/wiki/File:Sledgehammers-1.jpg",
  "Wire Strippers": "https://commons.wikimedia.org/wiki/File:Wire_strippers_5.jpg",
  "Screw Extractor": "https://commons.wikimedia.org/wiki/File:Screw_extractor_and_T-wrench.jpg",
  "Jigsaw": "https://commons.wikimedia.org/wiki/File:Ryobi_RJS_720_-_2017-01-19_(1).jpg",
  "Hedge Trimmer": "https://commons.wikimedia.org/wiki/File:Cordless_electric_hedge_trimmer_2.jpg",
  "Pruning Shears": "https://commons.wikimedia.org/wiki/File:Pruning_shears.jpg",
  "Soldering Station": "https://commons.wikimedia.org/wiki/File:Accta_301_Soldering_Station.png",
  "Bench Grinder": "https://commons.wikimedia.org/wiki/File:Work_shop_machines.bench_grinder.jpg",
  "Paint Roller": "https://commons.wikimedia.org/wiki/File:Paint_roller_3.jpg",
  "Cordless Drill": "https://commons.wikimedia.org/wiki/File:CORDLESS_DRILL.jpg",
  "Ratchet Set": "https://commons.wikimedia.org/wiki/File:Socket_set_with_two_ratchets_in_box.jpeg",
  "Grease Gun": "https://commons.wikimedia.org/wiki/File:Grease_gun_US_Military.jpg"
};