var twitchStreamers = {
  "Ninja": "https://commons.wikimedia.org/wiki/File:Ninja2019screenshot.jpg",
  "Pokimane": "https://commons.wikimedia.org/wiki/File:Pokimane_in_2019_in_a_Podcast.jpg",
  "Shroud": "https://commons.wikimedia.org/wiki/File:Shroud_cropped.jpg",
  "TimTheTatman": "https://commons.wikimedia.org/wiki/File:TimTheTatMan_at_Complexity_Launch_Event_2021.jpg",
  "xQc": "https://commons.wikimedia.org/wiki/File:XQc_at_S-Camp_2021.png",
  "Valkyrae": "https://commons.wikimedia.org/wiki/File:Valkyrae_for_100_Thieves_(cropped).jpg",
  "DrLupo": "https://commons.wikimedia.org/wiki/File:Dr_Lupo_threw_out_a_first_pitch_and_signed_a_billion_autos.jpg",
  "Asmongold": "https://commons.wikimedia.org/wiki/File:Asmongold_in_2022.jpg",
  "LilyPichu": "https://commons.wikimedia.org/wiki/File:Lilypichu,_fuslie,_albert_chang,_and_tj_brown_twitchcon_2018_(cropped).jpg",
  "MoistCr1TiKaL": "https://commons.wikimedia.org/wiki/File:Cr1TiKaL_in_2022.jpg",
  "TheRealKnossi": "https://commons.wikimedia.org/wiki/File:JensKnossalla.jpg",
  "Mizkif": "https://commons.wikimedia.org/wiki/File:Mizkif_October_2020_2.jpg",
  "Trainwreckstv": "https://commons.wikimedia.org/wiki/File:Trainwreckstv.jpg",
  "Jinnytty": "https://commons.wikimedia.org/wiki/File:Jinnytty_2021_01.png",
  "EsfandTV": "https://commons.wikimedia.org/wiki/File:Esfand_2022.jpg",
  "Sykkuno": "https://commons.wikimedia.org/wiki/File:Sykkuno_2020.png",
  "AuronPlay": "https://commons.wikimedia.org/wiki/File:AuronPlay_(2013).jpg",
  "Imaqtpie": "https://commons.wikimedia.org/wiki/File:Imaqtpie_at_IEM_Kiev.jpg",
  "Loserfruit": "https://commons.wikimedia.org/wiki/File:Loserfruit1.jpg",
  "Sodapoppin": "https://commons.wikimedia.org/wiki/File:Sodapoppin_scavenger_hunt_2021.jpg",
  "Nmplol": "https://commons.wikimedia.org/wiki/File:Nmplol_in_2023.jpg",
  "Greekgodx": "https://commons.wikimedia.org/wiki/File:Sodapoppin_with_Greekgodx_at_TwitchCon_2018_(cropped).png"
};