var NamedObject = {
	"Spatula": "https://commons.wikimedia.org/wiki/File:Spatula_II.JPG",
	"Wooden spoon": "https://commons.wikimedia.org/wiki/File:Wooden_Spoon.jpg",
	"Whisk": "https://commons.wikimedia.org/wiki/File:Whisk_Ball_03.jpg",
	"Tongs": "https://commons.wikimedia.org/wiki/File:Tongs_for_serving_food.jpg",
	"Ladle": "https://commons.wikimedia.org/wiki/File:Ladle.jpg",
	"Slotted spoon": "https://commons.wikimedia.org/wiki/File:Cuiller_%C3%A0_trous_04.jpg",
	"Serving fork": "https://commons.wikimedia.org/wiki/File:Serving_fork_MET_143236.jpg",
	"Potato masher": "https://commons.wikimedia.org/wiki/File:Kartoffelstampfer_2015.jpg",
	"Cake server": "https://commons.wikimedia.org/wiki/File:1024_Tortenheber-2791.jpg",
	"Meat tenderizer": "https://commons.wikimedia.org/wiki/File:Meat-Tenderizer.jpg",
	"Pizza cutter": "https://commons.wikimedia.org/wiki/File:Pizza-slicer.jpg",
	"Cheese grater": "https://commons.wikimedia.org/wiki/File:Cheese_grater.png",
	"Ice cream scoop": "https://commons.wikimedia.org/wiki/File:IceCreamScoop.jpg",
	"Can opener": "https://commons.wikimedia.org/wiki/File:Kitchen-Modern-Can-Opener.jpg",
	"Corkscrew": "https://commons.wikimedia.org/wiki/File:Corkscrew_P1150886.jpg",
	"Pastry brush": "https://commons.wikimedia.org/wiki/File:Kitchen-Silicone-Brush.jpg",
	"Melon baller": "https://commons.wikimedia.org/wiki/File:Kugelausstecher_30mm_Durchmesser.jpg",
	"Meat thermometer": "https://commons.wikimedia.org/wiki/File:2008-09-20_Thermometer_reading.jpg",
	"Lemon zester": "https://commons.wikimedia.org/wiki/File:Zester-stainless-steel.jpg",
	"Egg slicer": "https://commons.wikimedia.org/wiki/File:Eierschneider.jpg"
};