var vehiclesList = {
  "Lamborghini Aventador": "",
  "Ford Mustang": "",
  "Tesla Model S": "",
  "Ferrari 488": "",
  "Chevrolet Camaro": "",
  "BMW M3": "",
  "Audi R8": "",
  "Porsche 911": "",
  "Bugatti Veyron": "",
  "Jeep Wrangler": "",
  "Mercedes-Benz G-Class": "",
  "McLaren P1": "",
  "Volkswagen Beetle": "",
  "Rolls-Royce Phantom": "",
  "Dodge Challenger": "",
  "Toyota Supra": "",
  "Aston Martin DB11": "",
  "Nissan GT-R": "",
  "Jaguar F-Type": "",
  "Subaru WRX STI": "",
  "Land Rover Range Rover": "",
  "Mini Cooper": "",
  "Maserati GranTurismo": "",
  "Bentley Continental GT": "",
  "Ford F-150": "",
  "Chevrolet Corvette": "",
  "Volvo XC90": "",
  "GMC Sierra": "",
  "Honda Civic Type R": "",
  "Hyundai Tucson": "",
  "Kia Soul": "",
  "Lexus RX": "",
  "Mazda MX-5 Miata": "",
  "Mitsubishi Lancer Evolution": "",
  "Nissan 370Z": "",
  "Porsche Cayenne": "",
  "Subaru Outback": "",
  "Toyota Land Cruiser": "",
  "Volkswagen Golf GTI": "",
  "Jeep Grand Cherokee": "",
  "Dodge Viper": ""
}